"""Primary public package for interface-contract.

``strict_interface`` remains available as a fully compatible legacy import.
"""

from strict_interface import (
    AdaptationError,
    AdapterRegistry,
    AttributeSpec,
    Interface,
    InterfaceError,
    InterfaceMeta,
    Member,
    __version__,
    adapt,
    attributes_of,
    can_adapt,
    default,
    default_registry,
    implements,
    interface,
    interface_implement,
    is_abstract,
    is_interface,
    is_stub,
    members_of,
    missing_attributes,
    missing_members,
    register_adapter,
    satisfies,
    signature_problem,
    structurally_implements,
    unregister_adapter,
    verify,
    verify_instance,
)

__all__ = [
    "AdaptationError",
    "AdapterRegistry",
    "AttributeSpec",
    "Interface",
    "InterfaceError",
    "InterfaceMeta",
    "Member",
    "__version__",
    "adapt",
    "attributes_of",
    "can_adapt",
    "default",
    "default_registry",
    "implements",
    "interface",
    "interface_implement",
    "is_abstract",
    "is_interface",
    "is_stub",
    "members_of",
    "missing_attributes",
    "missing_members",
    "register_adapter",
    "satisfies",
    "signature_problem",
    "structurally_implements",
    "unregister_adapter",
    "verify",
    "verify_instance",
]
